---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: SonarCloud Scan

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - "master"
      - "feature*"

###############
# Set the Job #
###############
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      ###############- name: Analyze with SonarCloud
      ###############  uses: sonarsource/sonarcloud-github-action@master
      - name: HighByte Data
        uses: highbyte/sonarscan-dotnet@2.0
        with:
          # The key of the SonarQube project
          sonarProjectKey: nautymanish_ElevatorProblem
          # The name of the SonarQube project
          sonarProjectName:  ElevatorProblem
          # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
          sonarOrganization: nautymanish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
